sonar.projectKey=task-api
sonar.projectName=Task API
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**
